spring:
  application:
    name: Demo Application

logging:
  level:
    io.ms.lib: DEBUG
    springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.boot: INFO
    org.springframework.cloud: INFO